#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🏗️👷 Styling, testing your project before committing'

# Check ESLint Standards
yarn lint || (echo ' ❌ ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'; false;)

# Check Prettier standards
yarn check:format || (echo '❌ Prettier Check Failed. Run yarn format, add changes and try commit again.'; false;)

# Check tsconfig standards
yarn check:types || (echo '❌ Type Check Failed. Are you seriously trying to write that? Make the changes required above.'; false;)

# If everything passes... Now we can build
echo '🤔 ... Everything seems ok.'

yarn build || (echo '❌ Build Failed: View the errors above to see why.'; false;)

# If build success... Now we can commit
echo '✅ It is perfect!... I am committing this now.'
