name: Deploy on server prod (Lucky wheel be)

env:
  APP_ENV: ${{ secrets.PRODUCTION }}

on:
  push:
    branches: ['release']

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Pull code
        uses: actions/checkout@v3

      - name: Extract env file multi line.
        run: |
          rm -r -f .env
          touch .env_temp
          echo $APP_ENV | tee .env_temp
          sed 's/ /\n/g' .env_temp >> .env
          rm -r -f .env_temp

      - name: Build image and package
        run: |
          docker build -t lucky-wheel-be-production .
          docker save -o lucky-wheel-be-production.tar lucky-wheel-be-production

      - name: Copy Docker image from github action server to aws ec2 use SSH Key to login
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.PROD_SERVER_HOST }}
          username: ubuntu
          port: 22
          key: ${{ secrets.PROD_SERVER_KEY_SSH }}
          source: 'lucky-wheel-be-production.tar,docker-compose-ssh-production.yml'
          target: '~/lucky-wheel-be-production'

      - name: Executing remote ssh commands using SSH Key to deploy backend
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.PROD_SERVER_HOST }}
          username: ubuntu
          port: 22
          key: ${{ secrets.PROD_SERVER_KEY_SSH }}
          script_stop: true
          script: |
            cd ~/lucky-wheel-be-production
            sudo docker load --input lucky-wheel-be-production.tar
            sudo docker-compose -f docker-compose-ssh-production.yml  up -d --force-recreate
            rm -rf lucky-wheel-be-production.tar
            sudo docker image prune -a -f
