name: Check health server every 15 minutes

# on:
#   schedule:
#     - cron: '*/15 * * * *' # Runs every 15 minutes\

on:
  push:
    branches: ['test-github-action-schedule']

jobs:
  ping_server:
    runs-on: ubuntu-latest

    steps:
      - name: Check backend prod
        run: curl https://aapi.quayso-mayman.vn

      - name: Check backend stage
        run: curl https://bstage-be.quayso-mayman.vn
